defaults:
  - _self_
  - camera

storage_path: "/home/bobby/data/extracted_data/pick_bottle_from_fridge_left_robot"
demo_num: 0
collect_img: True
collect_depth: True
collect_state: True
collect_reskin: False
