defaults:
  - _self_
  - camera

# storage_path: "/home/siddhant/data_pb/extracted_data/0914_calibration"
storage_path: "/home_shared/grail_siddhant/data_pb/extracted_data/0914_mug_on_plate_human"
demo_num: 0
collect_img: True
collect_depth: False
collect_state: True
collect_reskin: False
